version: '2'
services:
    g-app:
        image: g
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=g-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    g-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: g-cassandra
    g-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=g-cassandra
    g-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: g-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
